### ISSUE TITLE
Re-centering and calibration UI buttons

### ISSUE THREAD

**Issue by SkyLeite** [wheaney/decky-xrealAir#4]
Hey! First of all, thanks for this driver. It fixes one of my biggest issues with the NReal Air.

That said, would it be possible to add UI buttons for the recentering and calibration actions? I'm personally having trouble getting the device to recognize the gestures, and it would be nice to be able to invoke them without taking my hands off the Deck.

**Comment by wheaney** [comment]
Yes, possible, but I actually don't have a great mechanism for triggering that. I know it sounds odd because I'm communicating configs to the plugin, but in that case it's writing a modification to the config file, and triggering a screen recenter isn't really a configuration, and the driver never modifies the file itself so it has no way to clear out a transient entry like that.

But thanks for filing this as it'll probably be a common request that I'll have to follow up on eventually.

Regarding the taps not working well for you, would you mind helping me debug?
1. `~/bin/xreal_driver_config --debug taps`
2. `truncate -s 0 ~/.xreal_driver_log`
3. Attempt to do some recentering and recalibration taps
4. Send me your `~/.xreal_driver_log`

**Comment by SkyLeite** [comment]
Sure. Could I run those commands over an ssh session while still in game mode, or should I run them in the desktop session?

**Comment by wheaney** [comment]
SSH session is fine, all configs can be changed on-the-fly without having to stop a game or unplug.

**Comment by wheaney** [comment]
I actually haven't heard this sentiment at all from the XREAL community since announcing the update, so I'll probably leave this request on the back-burner for now since it would require building another mechanism for communicating with the systemd service.

**Comment by wheaney** [comment]
I'm working on pulling in a change to the XREAL driver that requires a more complex calibration workflow (i.e. settings the glasses down and responding to some prompts), so I'm building this out now. I've updated the driver to support sending a device state to the UI and reading control flags from the UI. Decky changes are WIP.

**Comment by wheaney** [comment]
Buttons for recenter/recalibrate are now in the decky UI, in the production store.
